config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :plays do
    resources :reviews
  end
  root 'plays#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :plays
end

app/models/play.rb
class Play < ApplicationRecord
  belongs_to :user
  belongs_to :category
  has_many :reviews

  has_attached_file :play_img, styles: { play_index: "250x350>", play_show: "325x475>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :play_img, content_type: /\Aimage\/.*\z/
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :play
  belongs_to :user
  validates_numericality_of :rating, less_than: 5, message: 'must be between 0 and 5'

  def blank_stars
    5 - rating.to_i
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :plays
  has_many :reviews
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/plays_controller.rb
class PlaysController < ApplicationController
  before_action :find_play, only: %i[show edit update destroy]
  before_action :correct_user, only: %i[edit update destroy]
  before_action :authenticate_user!, only: %i[new edit]

  def index
    if params[:category].blank?
      @plays = Play.all.order('created_at DESC')
    else
      @category_id = Category.find_by(name: params[:category]).id
      @plays = Play.where(category_id: @category_id).order('created_at DESC')
    end
  end

  def show
    if @play.reviews.blank?
      @average_review = 0
    else
      @average_review = @play.reviews.average(:rating).round
    end
  end

  def new
    @play = current_user.plays.build
    @categories = Category.all.map { |c| [c.name, c.id] }
  end

  def create
    @play = current_user.plays.build(play_params)
    @play.category_id = params[:category_id]

    if @play.save
      redirect_to root_path
    else
      render 'new'
    end
  end

  def edit
    @categories = Category.all.map { |c| [c.name, c.id] }
  end

  def update
    @play.category_id = params[:category_id]

    if @play.update(play_params)
      redirect_to play_path
    else
      render 'edit'
    end
  end

  def destroy
    @play.destroy
    redirect_to root_path
  end

  private

  def play_params
    params.require(:play).permit(:title, :description, :director,
                                 :category_id, :play_img)
  end

  def find_play
    @play = Play.find(params[:id])
  end

  def correct_user
    redirect_to @play if current_user != @play.user
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :find_play
  before_action :find_review, only: %i[edit update destroy]
  before_action :authenticate_user!, only: %i[new edit]

  def new
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @review.play_id = @play.id
    @review.user_id = current_user.id

    if @review.save
      redirect_to play_path(@play)
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @review.update(review_params)
      redirect_to play_path(@play)
    else
      render 'edit'
    end
  end

  def destroy
    @review.destroy
    redirect_to play_path(@play)
  end

  private

  def find_play
    @play = Play.find(params[:play_id])
  end

  def find_review
    @review = Review.find(params[:id])
  end

  def review_params
    params.require(:review).permit(:rating, :comment)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/plays_helper.rb
module PlaysHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Broadway</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container">
        <%= link_to "Broadway", root_path, class: "navbar-brand" %>

        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarNavDropdown">
          <ul class="navbar-nav">
            <% if user_signed_in? %>
              <li class="nav-item"><%= link_to "Add Play", new_play_path, class: 'nav-link'%></li>
            <% end %>


            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Gender
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                <% Category.all.each do |category| %>
                  <a class="dropdown-item" href="#"><%= link_to category.name, plays_path(category: category.name) %></a>
                <% end %>
              </div>
            </li>
          </ul>
        </div>

        <ul class="navbar-nav justify-content-end">
          <% if user_signed_in? %>
            <li class="nav-item"><%= link_to "Sign Out", destroy_user_session_path, method: :delete, class: 'nav-link' %></li>
          <% else %>
            <li class="nav-item"><%= link_to "Sign Up", new_user_registration_path, class: 'nav-link' %></li>
            <li class="nav-item" ><%= link_to "Log In", new_user_session_path, class: 'nav-link' %></li>
          <% end %>
        </ul>
      </div>
    </nav>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <div class="container">
      <%= yield %>
    </div>


  </body>
</html>

app/views/plays/_form.html.erb
<%= simple_form_for @play do |f| %>
  <%= select_tag(:category_id, options_for_select(@categories, @play.category_id), :prompt => "Select Category") %>
  <%= f.file_field :play_img %>
  <%= f.input :title, label: 'Play title' %>
  <%= f.input :description %>
  <%= f.input :director %>
  <%= f.button :submit %>
<% end %>

app/views/plays/edit.html.erb
<h1>Edit Broadway Play</h1>
<%= render 'form' %>

app/views/plays/index.html.erb
<h1 class="current_category"> <%= params[:category] %></h1>

<% if @plays.count == 0 %>
  <h3>There are no plays in this category<h3>
<% else %>
  <div class="row">
    <% @plays.each do |play| %>
      <div class="col-md-3">
        <a href="/plays/<%= play.id %>">
          <%= image_tag play.play_img.url(:play_index), class: 'play' %>
        </a>
      </div>
    <% end %>
  </div>
<% end %>

app/views/plays/new.html.erb
<h1>New Broadway Play</h1>
<%= render 'form' %>

app/views/plays/show.html.erb
<div class="row">
  <div class="col-md-4">
    <%= image_tag @play.play_img.url(:play_show), class: 'play-show' %>
  </div>

  <div class="col-md-8">
    <div class="play-info">
      <h2 class="play-title"><%= @play.title %></h2>
      <h3 class="play-director"><span>From </span><%= @play.director %></h3>
      <h4 class="play-director"><%= @play.category.name %></h4>
      <h4 class="avg-rating"> Avarege Rating</h4>
        <div class="avg-review-rating">
          <% @average_review.times do %>
            <span class="glyphicon glyphicon-star"></span>
          <% end %>
        </div>
        <span class="number of review"><em>From: </em><%= @play.reviews.count %> reviews</span>
      <p class="play-desc"><%= @play.description %></p>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-md-12">
    <div class="reviews">
      <h1>Reviews</h1>
      <%= render @play.reviews %>
      <div>
        <%= link_to 'Add Reviews', new_play_review_path(@play), class: 'btn-custom' %>
      </div>
    </div>
  </div>
</div>

<div class="links btn-group">
  <% if @play.user == current_user %>
    <%= link_to 'Edit', edit_play_path(@play), class: 'btn btn-custom' %>
    <%= link_to 'Delete', play_path(@play), method: :delete, data: { confirm: 'Are you sure' }, class: 'btn btn-custom' %>
  <% end %>
</div>

app/views/reviews/_form.html.erb
<%= simple_form_for ([@play, @play.reviews.build]) do |f| %>
  <div id="errors">
     <ul>
      <% @review.errors.full_messages.each do |msg| %>
        <li> <%= msg %> </li>
      <% end %>
    </ul>
  <div>
  <div id="rating-form">
    <%= f.input :rating %>
  </div>
  <%= f.input :comment %>
  <%= f.button :submit, class: 'btn-custom2' %>
<% end %>

app/views/reviews/_review.html.erb
<div class="review">
  <% review.rating.to_i.times do  %>
    <span class="glyphicon glyphicon-star"></span>
  <% end %>
  <% review.blank_stars.times do %>
    <span class="glyphicon glyphicon-star-empty"></span>
  <% end %>
	<p class="review-comment"><%= review.comment %></p>
  <div class="links btn-group">
    <% if review.user == current_user %>
      <%= link_to 'Edit', edit_play_review_path(review.play, review), class: 'btn btn-custom' %>
      <%= link_to 'Delete', play_review_path(review.play, review), method: :delete, data: { confirm: 'Are you sure' }, class: 'btn btn-custom' %>
    <% end %>
  </div>
</div>

app/views/reviews/edit.html.erb
<div class="col-md-10 col-md-offset-1">
  <div class="edit-review-form">
    <h1>Edit review</h1>
    <%= simple_form_for ([@play, @review]) do |f| %>
      <div id="rating-form">
        <%= f.input :rating %>
      </div>
      <%= f.input :comment %>
      <%= f.button :submit, class: 'btn-custom2' %>
    <% end %>
  </div>
</div>

app/views/reviews/new.html.erb
<div class="col-md-10 col-md-offset-1">
  <div class="new-review-form">
    <h1>Post review</h1>
    <%= render 'form' %>
  </div>
</div>